In [2]:
import pandas as pd
import pymovements as pm
from pathlib import Path

/Users/caleblee/Projects/USRA2026/fcaEye/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
folder = "000000_20261023_2"
dir = Path("../data") / folder

In [4]:
trials  = pd.read_csv(dir / f"{folder}_trials.csv",  dtype={"participantID": str})
session = pd.read_csv(dir / f"{folder}_session.csv", dtype={"participantID": str})
gaze = pd.read_csv(dir / f"{folder}_gaze.csv", dtype={"participantID": str, "whereGaze": str})

/var/folders/n7/1ghh93yj0qg2phh5fjwjm8mc0000gn/T/ipykernel_71233/2193239152.py:3: DtypeWarning: Columns (0: trialRecorded, 1: phase, 2: blockStatus, 3: targetObj, 4: previousObj) have mixed types. Specify dtype option on import or set low_memory=False.
  gaze = pd.read_csv(dir / f"{folder}_gaze.csv", dtype={"participantID": str, "whereGaze": str})

In [5]:
gaze.head(10)

,participantID,Timestamp,psychopyTime_s,trialN,trialRecorded,phase,block,attempt,blockStatus,targetObj,previousObj,trialPhase,gazeX,gazeY,gazeUnits,region,whereGaze
0,000000,2000,47.9078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-99.1925,45.3513,screen_px,other,NaN
1,000000,4000,47.9098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-101.8930,45.5759,screen_px,other,NaN
2,000000,6000,47.9118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-101.0439,41.1936,screen_px,other,NaN
3,000000,8000,47.9138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-101.0847,42.1022,screen_px,other,NaN
4,000000,10000,47.9158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-103.0715,43.8509,screen_px,other,NaN
5,000000,12000,47.9178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-100.9098,46.5152,screen_px,other,NaN
6,000000,14000,47.9198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-100.4352,44.7215,screen_px,other,NaN
7,000000,16000,47.9218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-100.8505,43.9324,screen_px,other,NaN
8,000000,18000,47.9238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-100.8610,42.3924,screen_px,other,NaN
9,000000,20000,47.9258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,before_trials,-101.3491,41.8664,screen_px,other,NaN

In [6]:
trials.head(10)

,participantID,phase,block,attempt,stimSet,blockSeed,feedback,trialN,targetObj,previousObj,...,response_s,feedbackOn_s,blankOn_s,dotOnTracker_us,fixationHeldTracker_us,namesOnTracker_us,objectOnTracker_us,responseTracker_us,feedbackOnTracker_us,blankOnTracker_us
0,000000,practice,1,1,practice,6085,True,1,g7,NaN,...,54.182139,54.198265,56.206247,1636500,3858500,3878500,4875500,6274250,6290250.0,8298375
1,000000,learning1,1,1,phase1,7900,True,2,g7,NaN,...,63.038940,63.055737,65.062497,10386500,12634375,12658375,13619500,15130125,15146125.0,17154250
2,000000,learning1,1,1,phase1,7900,True,3,g0,g7,...,71.080145,71.096580,73.104489,18157375,20193500,20209500,21124625,23170750,23188750.0,25196875
3,000000,learning1,1,1,phase1,7900,True,4,g1,g0,...,78.721863,78.738704,80.745474,26202000,28250125,28268000,28933500,30811750,30829750.0,32835875
4,000000,learning1,1,1,phase1,7900,True,5,g1,g1,...,86.113174,86.130426,88.138374,33842875,35891000,35907000,36674375,38204875,38220875.0,40227125
5,000000,learning1,1,1,phase1,7900,True,6,g7,g1,...,93.688727,93.705469,95.713759,41234125,43284250,43300250,44151500,45780000,45798000.0,47804125
6,000000,learning1,1,1,phase1,7900,True,7,g5,g7,...,101.713353,101.729470,103.737312,48809125,50857250,50873250,51706500,53802625,53820625.0,55828750
7,000000,learning1,1,1,phase1,7900,True,8,g5,g5,...,109.254827,109.271992,111.278362,56831750,58865875,58881875,59797125,61345625,61363625.0,63369750
8,000000,learning1,1,1,phase1,7900,True,9,g4,g5,...,116.846647,116.863003,118.870615,64372875,66423000,66441000,67390125,68936625,68952625.0,70960875
9,000000,learning1,1,1,phase1,7900,True,10,g2,g4,...,124.321667,124.338227,126.344936,71965875,74016000,74032000,74699375,76411750,76429750.0,78436000

In [12]:
print(session.columns)

Index(['participantID', 'sonaID', 'age', 'gender', 'groupCell',
       'phase2Relation', 'sessionStart', 'pythonVersion', 'psychopyVersion',
       'os',
       ...
       'CALIBRATION.viewDist_mm', 'CALIBRATION.screenSize_mm',
       'CALIBRATION.targets_deg', 'CALIBRATION.setupDelay_ms',
       'CALIBRATION.minFixDur_ms', 'CALIBRATION.fixTimeout_s',
       'CALIBRATION.fixThreshold_px', 'CALIBRATION.fixInDot_deg',
       'CALIBRATION.fixOutDot_deg', 'CALIBRATION.calibrationCriterion_deg'],
      dtype='str', length=119)